### ISSUE TITLE
Splitting SearchView and Results.

### ISSUE THREAD

**Issue by Fedor-Tsyganov** [arimorty/floatingsearchview#104]
Is it possible to split searchview and list of results? I want to have a small gap between these two views like in Google Maps.

![5994_f](https://cloud.githubusercontent.com/assets/5728660/17232018/0f94c6d8-54da-11e6-9417-4626c560387a.jpg)

 Thanks.

**Comment by arimorty** [comment]
Hi @Fedor-Tsyganov ,

The main feature of this library is the smooth animation of the search suggestions, what you want to achieve is something else. So the answer is no, although this can easily be achieved, this library does not support it.

Regards,
Ari
