### ISSUE TITLE
We use your awesome library ;)

### ISSUE THREAD

**Issue by narko** [arimorty/floatingsearchview#106]
Hi,
I just wanted to let you know that we are using your awesome library in our little project. Keep it up!
https://play.google.com/store/apps/details?id=com.sixtytwentypeaks.recycl3r

Thanks!

**Comment by drjunior** [comment]
Hey, and here are two other apps with a thousand users also using this great lib. 
https://play.google.com/store/apps/details?id=com.setegraus.dicio
https://play.google.com/store/apps/details?id=com.cbcnos.sinonimos

Thanks arimorty!

**Comment by arimorty** [comment]
Hi @narko and @drjunior ,

Thanks for letting me know. I really appreciate the feedback and hope others will follow suit. I downloaded the apps and they look great!

Thanks for your support,
Ari

**Comment by joydeepsaha05** [comment]
Using this in my app too.
https://play.google.com/store/apps/details?id=ss.delta.com.trackmyshows

Really great and easy to implement. Thanks a lot @arimorty!

**Comment by arimorty** [comment]
Thanks for the feedback @joydeepsaha05 your app looks really good!

**Comment by ibnekhan** [comment]
Hi @narko

**Comment by usmaniqbal998** [comment]
how can i add suggestions to this search ?
