### ISSUE TITLE
Graphical issue text

### ISSUE THREAD

**Issue by felixkorch** [arimorty/floatingsearchview#108]
Hey! Great library :-)

Does anyone know how to fix this? Make the text stop before overlapping the clear button?
Also is it possible to add a onLongPressedItemClickListener to clear a search suggestion, or are there any other easy way?
![screenshot_20160803-222727](https://cloud.githubusercontent.com/assets/19212173/17381058/67df297e-59ca-11e6-9504-dff063704401.png)

**Comment by arimorty** [comment]
this is mentioned in issue #102, I will put out a fix for that in the next release.
