### ISSUE TITLE
Hamburger icon

### ISSUE THREAD

**Issue by ghost** [arimorty/floatingsearchview#109]
Hi, i've just started to implement your library but i've come across an issue that you may not be aware of.

The hamburger icon doesn't change from the back to the hamburger icon if you swipe the nav drawer away.

And i also have a feature request
You can't flagnoextractui (I know its little but i'd prefer to have it)

So please take these into consideration,

Thanks,
Jack

**Comment by ghost** [comment]
I'm sorry i found out how to fix all issues i'm sorry 👍

**Comment by arimorty** [comment]
Hi @JackRoberts1998, 

I am glad you found a solution, the sample app demonstrates how to deal with the nav hamburger.

Regards,

**Comment by ghost** [comment]
I do apologise, your library is amazing !!!!!!!!!!!!!!!
