### ISSUE TITLE
A way to hide menu items

### ISSUE THREAD

**Issue by ghost** [arimorty/floatingsearchview#110]
Hi me again,

With your library i can't seem to find a way to hide a menu item in java like menu.findItem(R.id.menuitem).setVisible(false);

Is there any way to do it ?

Thanks,
Jack

**Comment by arimorty** [comment]
That would be a challenge with this library, if not impossible. What you can do instead is to have different menu xmls for different states and [re-inflate](https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L991) them at runtime as needed. 

Regards,
