### ISSUE TITLE
A way to disable home button in left menu

### ISSUE THREAD

**Issue by royale1223** [arimorty/floatingsearchview#111]
I'm using the left menu to open a drawer. When it's clicked a home button is shown. Is there a way to disable it?

**Comment by arimorty** [comment]
Hi, 

Please refer to the sample app, it handles such a case.

Regards,

**Comment by royale1223** [comment]
Alright

**Comment by royale1223** [comment]
For the sake of documentation here's the solution:

```
        mDrawerLayout.addDrawerListener(new DrawerLayout.DrawerListener() {
            @Override
            public void onDrawerSlide(View drawerView, float slideOffset) {
            }

            @Override
            public void onDrawerOpened(View drawerView) {

                //since the drawer might have opened as a results of
                //a click on the left menu, we need to make sure
                //to close it right after the drawer opens, so that
                //it is closed when the drawer is  closed.
                mSearchView.setLeftMenuOpen(false);
            }

            @Override
            public void onDrawerClosed(View drawerView) {
            }

            @Override
            public void onDrawerStateChanged(int newState) {
            }
});
```

**Comment by arimorty** [comment]
@royale1223 , your question brought to my attention that configuring the menu button with the navigation drawer is not very straightforward, so I added a feature to milestone 2.0.3 to ease the process. Have a look at [this](https://github.com/arimorty/floatingsearchview/commit/23d24cb5c0159a0eb5d99b247fc0cb32f2cad2d6)  commit.

Thanks for bringing this issue to my attention,
Ari
