### ISSUE TITLE
mTextColor in SearchSuggestionsAdapter doesn't used

### ISSUE THREAD

**Issue by skrugly** [arimorty/floatingsearchview#116]
It's impossible to change suggestion's TextView color

**Comment by arimorty** [comment]
Hi @Adambl4 ,

As you can see from the example [here](https://github.com/arimorty/floatingsearchview/blob/master/sample/src/main/java/com/arlib/floatingsearchviewdemo/fragment/SlidingSearchResultsExampleFragment.java#L216) , you can access the `TextView` dynamically. You can also set the text color for all items using [this](https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L788).

Regards,
Ari
