### ISSUE TITLE
How can I listen for clear button (x) press?

### ISSUE THREAD

**Issue by CillianMyles** [arimorty/floatingsearchview#118]
Hello,

Firstly, thanks for the great work.

My question is how would you advise to listen for clear button press?
At the moment I am using the OnQueryChangeListener like so:

```
        mSearchBar.setOnQueryChangeListener(new FloatingSearchView.OnQueryChangeListener() {
            @Override
            public void onSearchTextChanged(String oldQuery, String newQuery) {
                if (!TextUtils.isEmpty(oldQuery) && TextUtils.isEmpty(newQuery)) {
                    // There was some query but it was removed.
                    // Reset all searches / filters etc.
                    sendResetEvent();
                }
            }
        });
```

But this listener does not differentiate between clicking the clear button (x) which clears text, and manually clearing the text by pressing backspace on the soft keyboard.

Any idea how I could achieve this?
Thanks in advance!

**Comment by arimorty** [comment]
Hi @CillianMyles ,

It will be a good idea to include a callback for that. I will add it to the next milestone.

In the meanwhile, the only way to distinguish them that I can think of is when the input text's length is >= 2 when the clear button is clicked. If that's enough for you, you can do something like:

`
if(Math.abs(oldQuery.length() - newQuery.length()) >= 2){
                    Toast.makeText(getContext(), "oops, it's from clear btn", Toast.LENGTH_SHORT).show();
                }
`

The idea here is that the only time that the distance between the lengths of the old and new query  is >= 2 is when clear is clicked. Again, this doesn't work when the old query is < 2.

As I said, it will definitely be included in the next release.

Thanks for bringing up this needed feature,
Ari

**Comment by CillianMyles** [comment]
Hi @arimorty,

Once I had asked the question, I actually began to see this solution. 
Thanks for the prompt response. 

In the solution for the next release, it will be able to distinguish the case where going from single character search to none - newQuery.length() = 0, and oldQuery.length() = 1 - yes?
You could just make a call to the listener here? https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L577-L579

Do you think it should be more complicated than this? If you don't think so, or if you need help, I could help with a PR if you like. 

Thanks again for the good work. 
I have one other small bit of feedback actually, will I post here or add as a separate question?

Regards,
Cillian

**Comment by arimorty** [comment]
Adding this functionality is fairly straightforward, but the thing is that releasing each version of this library takes time (it's more than just merging) so the only thing I can do is add this to the list of features for the next release and then release it as part of larger release.

 Having said that, you can still submit  PR if you feel like you can implement it, but the code in the PR should be focused (don't change anything else)

**Comment by CillianMyles** [comment]
Okay if I get a chance I will submit a focused PR.
Thanks again!

**Comment by metinvio** [comment]
mSearchView.setOnClearSearchActionListener { println("CLEAR clicked") }
