### ISSUE TITLE
Add Suggestion

### ISSUE THREAD

**Issue by KingOfBeer** [arimorty/floatingsearchview#12]
How can i add suggestion to this persistent search? for example i want to add array of string and icons

sorry for my english

**Comment by arimorty** [comment]
You don't add suggestions, you swap (replace) the existing suggestions by calling   `mSearchView.swapSuggestions(data);` Where data is a list of objects that implement `SearchSuggestion`. You can call it at any time, but you typically would want to do it when text changes in the input. I other words, listen for changes, and swap items as follows:

```
mSearchView.setOnQueryChangeListener(new FloatingSearchView.OnQueryChangeListener() {
            @Override
            public void onSearchTextChanged(String oldQuery, final String newQuery) {

              mSearchView.swapSuggestions(data);
            }
        });
```

Everything is demonstrated in the sample, have a look at it.

Enjoy,

**Comment by shubhrajps** [comment]
Can anyone please give me code to add it. I am unable to understand. Full code for adding suggestions will be very helpful
