### ISSUE TITLE
Landscape Mode

### ISSUE THREAD

**Issue by Stashare** [arimorty/floatingsearchview#127]
In landscape mode the keyboard no longer takes the whole screen, but it works as in portrait mode, making some room for the suggestions to be displayed. How can i solve this mess?

**Comment by Komatoz** [comment]
I have the same problem.
In landscape mode after tap on the search view - suggestions are showing, keyboard isn't showing. 

After double tap - fullscreen editing mode, keyboard is showing, suggestions aren't showing. 

android:imeOptions="actionSearch|flagNoExtractUi" doesn't help for me. 

How can I fix that?

**Comment by deividas717** [comment]
same problem here....
