### ISSUE TITLE
How to handle the soft keyboard search event?

### ISSUE THREAD

**Issue by SilverFoxA** [arimorty/floatingsearchview#131]
We don't have access to the edit text within the search view thus performing 
`onEditorActionListener()`
doesn't work. Moreover overriding the 
`onKeyDown()` or `onKeyUp()` won't help either because of the soft keyboard.

If the solution is available please do share, if not I believe we are looking for an enhancement here to interact with the edit text inside.

**Comment by arimorty** [comment]
Hi @SilverFoxA ,

It could be a good idea to create a getter for the `EditText` in future releases of the library. For now, you can just get the `EditText` using its id (the library itself doesn't set the editor action listener, so you are safe setting it in your code). 

`((TextView)mSearchView.findViewById(R.id.search_bar_text)).setOnEditorActionListener(...);
`

Regards,
Ari
