### ISSUE TITLE
Progress spinner?

### ISSUE THREAD

**Issue by Permusoft** [arimorty/floatingsearchview#132]
I see how to add a menu to the right side of your search view… I’m hoping to put a dumb progress spinner there. Is there any way to do this?

**Comment by MarkyC** [comment]
@Permusoft There's [an API for this provided by FloatingSearchView](https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L967). However, it puts the progress bar on the left (beside the query).

I suppose you could create an [`AnimationDrawable`](https://developer.android.com/reference/android/graphics/drawable/AnimationDrawable.html) and set it as the icon on the menu item if you really want it on the right hand side.
