### ISSUE TITLE
Feature Request: No suggestions found

### ISSUE THREAD

**Issue by joydeepsaha05** [arimorty/floatingsearchview#133]
It would be nice to have an out-of-box implementation of displaying a "No suggestions found" drop-down whenever suggestions could not be found (this would be set by the developer).

This could also be expanded to display a connectivity issue message whenever the suggestions are loaded via a network call.

**Comment by arimorty** [comment]
@joydeepsaha05 This is easily achievable with the current api. Just create a `SearchSuggestion` with your desired message and icon.

I will consider if it makes sense to include it as a feature in the next release.

Thanks,
