### ISSUE TITLE
Suggestions not floating as expected

### ISSUE THREAD

**Issue by wanclem** [arimorty/floatingsearchview#134]
So hey there,this is  great work I must say I appreciate..Am using your library but am faced with an issue now...I can't seem to make the suggestions listview float as shown in your second gif...It always seem to push my other main listview downwards which is not what I want.Below is the effect I want,let the suggestions listview float above my other listview and not ontop of it, z-order..Thanks

![Effect I want](https://github.com/arimorty/floatingsearchview/blob/master/images/1506tq.gif)

**Comment by arimorty** [comment]
Hi @WanClem ,

The library in itself doesn't scroll the search results, you have to implement it on your side. Assuming that you are using the sample app as a reference, [this line](https://github.com/arimorty/floatingsearchview/blob/master/sample/src/main/java/com/arlib/floatingsearchviewdemo/fragment/SlidingSearchResultsExampleFragment.java#L250) makes the search results scroll, so just remove it and it won't scroll.

Regards,
Ari
