### ISSUE TITLE
Add ability to manipulate the overview menu's items

### ISSUE THREAD

**Issue by maxee** [arimorty/floatingsearchview#137]
It would be very nice to have the ability to manipulate the items of the overflow menu (e.g. set their checked state, etc.).
Therefore it would be nice to have a method let's say `getOverflowMenu()` which returns a Menu object or making the existing method `inflateOverflowMenu(int)` return the inflated Menu object.

**Comment by arimorty** [comment]
Hi @maxee ,

I agree with you, thanks for bringing this to my attention. Will include it in next release.

**Comment by maxee** [comment]
@arimorty I created some changes addressing this issue in #142.
