### ISSUE TITLE
Pagination / listen for scroll to bottom

### ISSUE THREAD

**Issue by inlacou** [arimorty/floatingsearchview#138]
Hi, first of all thanks for this awesome library.

I have been looking, but have not seen any way to achieve pagination. Is there a way to do it?

I saw a `OnScrollChangeListener`, but it's only available from API lvl 21 and above :s

Thanks in advance.

**Comment by arimorty** [comment]
Hi @inlacou ,

Are you asking about pagination in the search suggestions or in general?

**Comment by inlacou** [comment]
Hi,

In suggestions.
