### ISSUE TITLE
Requesting persistent clear (x) button

### ISSUE THREAD

**Issue by Permusoft** [arimorty/floatingsearchview#141]
It would be nice for my users to be able to clear the search text without an extra touch -- by leaving the clear button available after focus clears the search view. It could also be a configuration option, or perhaps implemented as a pre-fab menu resource we can add to the right side.

**Comment by arimorty** [comment]
Hi @Permusoft ,

I hear what you are saying and will definitely consider it for the next release.

For now, you can have two menu xmls, one will have a clear button and will be used for when search is not focused and the other one won't have that clear button and will be used for when search is focused.
