### ISSUE TITLE
search_bar_text_size is too big

### ISSUE THREAD

**Issue by whollacsek** [arimorty/floatingsearchview#143]
`search_bar_text_size` is set to `16sp` but visually it is bigger than Google Maps (and other search bar library)

Please change the value or allow it to be changed by attr.

**Comment by thedude61636** [comment]
you can copy the existing search_query_section layout in the library to your layouts and customize it to your liking

**Comment by whollacsek** [comment]
Thanks for the reply, I'll try it.

**Comment by n-belokopytov** [comment]
I think that doing a font size attrib is 100 times easier than doing full customisation. Do you guys think it's going to be worth it?

**Comment by arimorty** [comment]
Makes sense to add this to the library. Will add an attribute `floatingSearch_searchSuggestionTextSize` in 2.0.4

Thanks everyone,
Ari
