### ISSUE TITLE
Set elevation of the searchBar

### ISSUE THREAD

**Issue by nicomazz** [arimorty/floatingsearchview#144]
I can't find a way to set the elevation of the searchBar. Is it possible?

**Comment by arimorty** [comment]
It's not possible to do out-of-the-box, but you can always do something like this:
`       ((CardView)mSearchView.findViewById(R.id.search_query_section)).setCardElevation(Util.dpToPx(50));
`

But bear in mind that it could mess up the look of the bottom of the search bar. I think it's worth experimenting.

Regards,
Ari
