### ISSUE TITLE
make background color customizable

### ISSUE THREAD

**Issue by whollacsek** [arimorty/floatingsearchview#146]
It'd be nice to be able to customize the background color through an attr. For example set the background to a solid color mimicking the behavior of Google Maps.

**Comment by arimorty** [comment]
Hi @whollacsek ,
There is an option for that `floatingSearch_backgroundColor` please look at the README at the bottom of the page.

Regards,
Ari

**Comment by whollacsek** [comment]
hi @arimorty what your are suggesting is changing the background color of the search bar and the suggestion section. What I'm proposing is to be able to change the color of the entire background, instead of dimming the background as right now.

**Comment by arimorty** [comment]
In that case, you can just set the `floatingSearch_dimBackground` attribute to `false` and then implement a background on your own. My opinion is that making the background white is considered a client-side feature from the library's perspective.

**Comment by whollacsek** [comment]
Ok I understand, what I did is wrapping the FloatingSearchView in a FrameLayout.
