### ISSUE TITLE
search_suggestions_section should take content's height only

### ISSUE THREAD

**Issue by whollacsek** [arimorty/floatingsearchview#149]
Currently `search_suggestions_section` occupy the entire screen even when no suggestion is showing. It should only take at most the height of the suggestion list.

I'm showing a recycle view under the FloatingSearchView when FloatingSearchView is in focus, but when it is in focus the user can not interact with the recycle view.

Pseudo layout:

```
<FrameLayout>
    <RecycleView />
    <FloatingSearchView />
</FrameLayout>
```

**Comment by arimorty** [comment]
Sorry for late response, but that's the intended behavior. I would suggest you to clone the repo and customize.

Regards,
Ari
