### ISSUE TITLE
Content Description for menu itens

### ISSUE THREAD

**Issue by othiagosouto** [arimorty/floatingsearchview#151]
Hi,  

The items from menu has no contentDescription, can i submit a push  to solve it?

Thank you, you did a great work!

**Comment by arimorty** [comment]
I know it's a late response, but didn't have time.

Thanks for your recognition!

Your suggestion is great and someone has already submitted a PR for it [here](https://github.com/arimorty/floatingsearchview/pull/101)

Thanks,
Ari
