### ISSUE TITLE
Visible Suggestions manipulation

### ISSUE THREAD

**Issue by n-belokopytov** [arimorty/floatingsearchview#155]
Please implement methods for "suggestions" manipulations, for example - get visible suggestions, select suggestion by pos, etc. All looks very simple and basic.

**Comment by arimorty** [comment]
Why not clone this repo and customize the code for your needs?

I noticed from your other issues as well that you have specific needs. This library isn't meant to provide out-of-the-box solutions for each use case. Instead, it's an effort to make it easier for the dev community to implement a material design concept by providing APIs for the most general use cases.

Thanks, and I hope you understand.
Ari
