### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by imtiazkalamabir** [arimorty/floatingsearchview#156]
Hi, im interested to use your library on my Google Maps activity.
I have a specific set of work for this. I need to fetch a set of data on suggestions for Listening to query changes and provide suggestion items that implement SearchSuggestion. the suggestions will be taken from an array. On clicking the suggestion item, it will put a marker on the same map activity. Can you give me directions on using this library for that please. Thanks in advance

**Comment by arimorty** [comment]
Sorry for the late response, but just listen for suggestion clicks using [setOnSearchListener()](https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L1602)

Regards,
Ari
