### ISSUE TITLE
custom adapter and custom child possbile?

### ISSUE THREAD

**Issue by parkjaeiek** [arimorty/floatingsearchview#16]
how set custom adapter and custom child?

**Comment by arimorty** [comment]
You can't, as of this moment.

Thanks for asking.

**Comment by apMadden** [comment]
@arimorty  Hey, I was wondering if there was any update on if custom adapters will eventually be possible. I have tried modifying your library myself but couldn't get it working. 

Thanks for the library though, by far my favorite floating searchview implementation I've found.
