### ISSUE TITLE
Help - how to onSuggestionsClick

### ISSUE THREAD

**Issue by NusDucHV** [arimorty/floatingsearchview#160]
I want listener when user click to Suggestion
Can you help me ?
Thanks

**Comment by arimorty** [comment]
Hi @NusDucHV ,

Do you need to listen when the user clicks a suggestion and the search bar collapses? If that's the case, you can just listen to focus changes as mentioned in the README.

**Comment by NusDucHV** [comment]
Okay.
I got it.
Thanks @arimorty

**Comment by usmaniqbal998** [comment]
can you tell how to add suggestions ?
