### ISSUE TITLE
Left icon bug?

### ISSUE THREAD

**Issue by Permusoft** [arimorty/floatingsearchview#161]
When the left icon is set to Hamburger, then to Home, then back to Hamburger, the Home icon remains. Please see demo at https://github.com/Permusoft/FSV-Icon-Bug-Demo.

I have had no luck with invalidating, requesting layout, and so on. In practice, triggering the FSV internal animation routines does cause the Hamburger to reappear.

Any work around is appreciated. Thanks for the great library!

**Comment by arimorty** [comment]
Thanks for the report! @Permusoft

**Comment by Permusoft** [comment]
I would like to help out -- if you make a suggestion I can do some work here!

**Comment by arimorty** [comment]
@Permusoft this is fixed and is in the develop branch, I usually wait for more code to be packed into develop before publishing to Maven since publishing is a process that takes some time.

Thanks!

**Comment by arimorty** [comment]
@Permusoft I would be interested in knowing where you are using this library. Feel free to drop me an email cmaricontact@gmail.com if you don't want to mention it here. If you can't give me this info, that's ok too, I understand.
