### ISSUE TITLE
Suggestion view slide under the fragment container

### ISSUE THREAD

**Issue by masoud-c** [arimorty/floatingsearchview#164]
Hi,
I'm using FloatingSearchView above a fragment container and when suggestions slide it goes under the fragment container.
how can I bring suggestions front?
this is the view:

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/main_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    <FrameLayout android:id="@+id/container"
                 android:layout_marginTop="?attr/actionBarSize"
                 android:layout_width="match_parent"
                 android:layout_height="match_parent"
                 app:layout_behavior="@string/appbar_scrolling_view_behavior"
                 tools:ignore="MergeRootFrame"/>

    <com.arlib.floatingsearchview.FloatingSearchView
            android:id="@+id/search_view"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:layout_gravity="top"
            app:floatingSearch_dismissOnOutsideTouch="true"
            app:floatingSearch_leftActionMode="showHamburger"
            app:floatingSearch_searchBarMarginLeft="10dp"
            app:floatingSearch_searchBarMarginRight="10dp"
            app:floatingSearch_searchBarMarginTop="2dp"
            app:floatingSearch_showSearchKey="true"
            app:floatingSearch_suggestionsListAnimDuration="250"
            app:floatingSearch_dimBackground="false"
            app:floatingSearch_close_search_on_keyboard_dismiss="false"/>
</android.support.design.widget.CoordinatorLayout>
```

**Comment by nowfalsalahudeen** [comment]
same problem here

any solution??
suggestion list behind the view ..how to bring it to front

**Comment by arimorty** [comment]
Simply don't use `CoordinatorLayout` for this, why would you? `CoordinateLayout` isn't a `FrameLayout` or a `RelativeLayout`. Unlike these two layouts, `CoordinateLayout` doesn't care for its child views' hierarchy or positions.

Regards,
Ari

**Comment by masoud-c** [comment]
I used FrameLayout too, same Result! problem is still there, any other solution?

**Comment by arimorty** [comment]
The sample app is working, why not look at the sample app? Or, alternatively, share your updated xml.

**Comment by masoud-c** [comment]
I did like the sample app, but it's still the same, used CoordinateLayout, FrameLayout and Relativelayout as root element.
this is the whole xml file:

<RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/main_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/purpul">

    <com.arlib.floatingsearchview.FloatingSearchView
            android:id="@+id/search_view"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:layout_gravity="top"
            app:floatingSearch_menu="@menu/menu_search"
            app:floatingSearch_dismissOnOutsideTouch="true"
            app:floatingSearch_leftActionMode="showHamburger"
            app:floatingSearch_searchBarMarginLeft="10dp"
            app:floatingSearch_searchBarMarginRight="10dp"
            app:floatingSearch_searchBarMarginTop="2dp"
            app:floatingSearch_showSearchKey="true"
            app:floatingSearch_suggestionsListAnimDuration="250"
            app:floatingSearch_dimBackground="false"
            app:floatingSearch_close_search_on_keyboard_dismiss="false"/>

    <FrameLayout android:id="@+id/container"
                 android:layout_width="match_parent"
                 android:layout_height="match_parent"
                 android:layout_below="@id/search_view"
                 app:layout_behavior="@string/appbar_scrolling_view_behavior"
                 tools:ignore="MergeRootFrame"/>

    <com.luseen.spacenavigation.SpaceNavigationView
            android:id="@+id/bottom_navigation"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            app:centre_button_icon="@drawable/ic_pin_around"
            android:layout_gravity="bottom"
            app:layout_behavior="com.luseen.spacenavigation.SpaceNavigationViewBehavior"/>

</RelativeLayout>

**Comment by arimorty** [comment]
Where is the CoordinateLayout placed?

**Comment by masoud-c** [comment]
this version has a RelativeLayout as root element. 

<RelativeLayout

        android:id="@+id/main_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/purpul">
            <FloatingSearchView .... />

            <FrameLayout ..../>

            <SpaceNavigationView ..../>
</RelativeLayout>`

**Comment by arimorty** [comment]
Ok, here the issue is apparent, the `FloatingSearchView` is placed at the top of the view tree, put it at the bottom and `RelativeLayout` or `FrameLayout` will draw it last causing it to be on top of the other elements.

**Comment by masoud-c** [comment]
still the same result, 
it has a FrameLayout as root element:
<FrameLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/main_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/purpul">

    <FrameLayout android:id="@+id/container"
                 android:layout_width="match_parent"
                 android:layout_height="match_parent"
                 android:layout_marginTop="?attr/actionBarSize"
                 app:layout_behavior="@string/appbar_scrolling_view_behavior"
                 tools:ignore="MergeRootFrame"/>

    <com.luseen.spacenavigation.SpaceNavigationView
            android:id="@+id/bottom_navigation"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:centre_button_icon="@drawable/ic_pin_around"
            android:layout_gravity="bottom"
            app:layout_behavior="com.luseen.spacenavigation.SpaceNavigationViewBehavior"/>

    <com.arlib.floatingsearchview.FloatingSearchView
            android:id="@+id/search_view"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:layout_gravity="top"
            app:floatingSearch_menu="@menu/menu_search"
            app:floatingSearch_dismissOnOutsideTouch="true"
            app:floatingSearch_leftActionMode="showHamburger"
            app:floatingSearch_searchBarMarginLeft="10dp"
            app:floatingSearch_searchBarMarginRight="10dp"
            app:floatingSearch_searchBarMarginTop="2dp"
            app:floatingSearch_showSearchKey="true"
            app:floatingSearch_suggestionsListAnimDuration="250"
            app:floatingSearch_dimBackground="false"
            app:floatingSearch_close_search_on_keyboard_dismiss="false"/>
</FrameLayout>

**Comment by arimorty** [comment]
That's really strange. Does this happen when you run the sample app on your device/emulator as well?

**Comment by masoud-c** [comment]
no, it's totally fine when I run the sample app on my device.

**Comment by arimorty** [comment]
There must be something in your code or xml that you are missing, try to compare your code with the sample.

**Comment by masoud-c** [comment]
the problem was the height of FloatingSearchView, I thought it's just the height of search box so I set it to ActionBarSize, it has to match parent.
thanks for your time
