### ISSUE TITLE
Build apk error

### ISSUE THREAD

**Issue by NusDucHV** [arimorty/floatingsearchview#165]
When I build app apk the android studio respond
"Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/arlib/floatingsearchview/FloatingSearchView$1.class"

**Comment by gauravbadarkhe** [comment]
Excluding support-v4 soles the problem
```
implementation ('com.github.arimorty:floatingsearchview:VERSION_NUMBER'){
        exclude module: 'support-v4'
    }

```
