### ISSUE TITLE
Question, Listen for clear selection action

### ISSUE THREAD

**Issue by OmarHassan25** [arimorty/floatingsearchview#168]
How i can listen for selected suggestion clear action?, If i selected a suggestion then clicked the X button to clear it, How i can catch this action ?

**Comment by arimorty** [comment]
Hi @OmarHassan25 ,

[onSearchTextChanged()](https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L223) is going to get called when you clear the current query as well.

Regards,
Ari
