### ISSUE TITLE
How can i add Logo ?

### ISSUE THREAD

**Issue by AruLNadhaN** [arimorty/floatingsearchview#169]
I need to add my Logo as a Drawable in the searchview Edit Text like Google Playstore. 
How can i acheive this ?

**Comment by arimorty** [comment]
Hi @AruLNadhaN , this isn't supported out of the box. But, feel free to import the library into your project and add the drawable to the xml. Or, just do something like ` ((TextView)mSearchView.findViewById(R.id.search_bar_text))
                .setCompoundDrawablesWithIntrinsicBounds( R.drawable.your_drawable, 0, 0, 0);`

Regards,
Ari
