### ISSUE TITLE
lefe menu color not change

### ISSUE THREAD

**Issue by parkjaeiek** [arimorty/floatingsearchview#17]
DrawableCompat.setTint(mIconBackArrow.mutate(), color);
        DrawableCompat.setTint(mIconSearch.mutate(), color);

fix this work

**Comment by arimorty** [comment]
Can you explain? I is difficult to see what your problem is.

**Comment by parkjaeiek** [comment]
@arimorty  sorry i not speak english very well T.T
my explain 

i use galaxys3 device left menu color white use -> but left arrow not white

so find source.... tint method drawable change drawable.mutate() so fixed....

**Comment by arimorty** [comment]
Issue is resolved in latest release.
