### ISSUE TITLE
Show menuItem title

### ISSUE THREAD

**Issue by rubenslopes** [arimorty/floatingsearchview#171]
When a menuItem showAsAction attribute is set to ifRoom, but has no icon show it's title instead of vertical dots

**Comment by arimorty** [comment]
Titles would take up too much space, don't you think? Let me know if you mean something else.

**Comment by rubenslopes** [comment]
Something like this http://d.pr/i/Lhx6, but "ANUNCIAR" should be inside the searchView like a expanded menuItem.

I think a single menuItem with a short title it is not a big deal

**Comment by arimorty** [comment]
The whole point of the vertical dots is to show that there is more options when there is not enough space to fit the options in. Text can have variable length so that would not work out here.
