### ISSUE TITLE
SearchView takes up whole screen

### ISSUE THREAD

**Issue by heraldofsolace** [arimorty/floatingsearchview#176]
I have a relativelayout just below the searchview. The RelativeLayout has a OnLongClickListener set.

![screenshot_20170212_152107](https://cloud.githubusercontent.com/assets/12252677/22861121/1e86b990-f137-11e6-8743-3343328cd00e.png)
However, if I set the layout_height of searchview to either of "match_parent" or "wrap_content", the searchview takes up the whole screen
![screenshot_20170212_152506](https://cloud.githubusercontent.com/assets/12252677/22861135/741665ae-f137-11e6-9da5-a8a8efc9bcd1.png)
And this makes the OnLongClickListener unusable, since the relativelayout is pushed to the bottom of the screen.

Is there any way to keep the searchview collapsed, and expand it only when needed?

**Comment by djdance** [comment]
Im using this

```
 mSearchView.postDelayed(new Runnable() {
            @Override
            public void run() {
               mSearchView.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, (int) (50*density)));
            }
        },500);
        mSearchView.setOnSuggestionsListHeightChanged(new FloatingSearchView.OnSuggestionsListHeightChanged() {
            @Override
            public void onSuggestionsListHeightChanged(float newHeight) {
                mSearchView.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, (int) (50*density+newHeight)));
            }
        });
```
