### ISSUE TITLE
FloatingSearchView in Toolbar (Google Play like)

### ISSUE THREAD

**Issue by ghost** [arimorty/floatingsearchview#18]
Is there a way i can achieve the same behaviour as in the new Google Play Store?
Tried every XML variant but it isnt working for me ( cause it needs to take full height in order to work with suggestions. But then the Toolbar height is full height (cause Search is nested in it))

My concern is on stackoverflow too, but no answers yet. If it is not a productive issue/concern, you can close it. Just curious if someone got it working somehow.

http://stackoverflow.com/questions/34311630/android-floatingsearchview-inside-toolbar

**Comment by arimorty** [comment]
Hi @markuspaschke,

To add to my answer on SO, although you can't use the scrolling effect using the Toolbar, it is likely that I will add some custom support for scrolling, I agree that it is a needed feature. 

In addition, if you would like to contribute to the project by adding the above feature or any other feature, let me know and I will publish a document about how the library works.

Thanks for your comment.

**Comment by apMadden** [comment]
Is there a document anywhere that gets it working?

**Comment by arimorty** [comment]
Hi @apMadden , Yes there is an example in the sample app.

**Comment by apMadden** [comment]
Hey @arimorty  thanks for the quick response. Looking at this now this isn't the right issue, my mistake.
