### ISSUE TITLE
floatingSearch_close_search_on_keyboard_dismiss - BUG

### ISSUE THREAD

**Issue by shifatul-i** [arimorty/floatingsearchview#183]
Hi,
if 
**floatingSearch_close_search_on_keyboard_dismiss="true"**
then
**onActivityBackPress()** do not work anymore on **BACK button** press, it closes the activity even when Search Suggestions are showing.

Note: 
_Sorry, I just noticed that this happens only for devices without keyboard (i.e. emulators)_

**Comment by arimorty** [comment]
@ThunderRoid  please save this project's maintainers time by closing issues that you resolved.

Thanks
