### ISSUE TITLE
ScrollingSearch Scroll

### ISSUE THREAD

**Issue by shifatul-i** [arimorty/floatingsearchview#184]
Hello, as you can see, in **Scrolling Search**, the suggestion list looks odd at the very end if one scrolls the suggestion list. This happens because the Search View gets out of the view.

![image](https://cloud.githubusercontent.com/assets/3328263/23105146/bfcbffd4-f68e-11e6-9c6a-eee4c6579657.png)

![image](https://cloud.githubusercontent.com/assets/3328263/23105147/c51dc81e-f68e-11e6-8bfd-a25b1c4414f2.png)

_Anyways, I just want to say thanks, this is an awesome library._

**Comment by arimorty** [comment]
I am not sure what you mean by Scrolling Search, but you are very welcome!

**Comment by shifatul-i** [comment]
I mean [ScrollingSearchExampleFragment.java](https://github.com/arimorty/floatingsearchview/blob/master/sample/src/main/java/com/arlib/floatingsearchviewdemo/fragment/ScrollingSearchExampleFragment.java)

If suggestion list is large, it brakes when scrolled down.
