### ISSUE TITLE
Stop back button from being shown when left action clicked using leftActionMode showHamburger

### ISSUE THREAD

**Issue by jbmlaird** [arimorty/floatingsearchview#185]
Great library.

I'm trying to implement [MaterialDrawer](https://github.com/mikepenz/MaterialDrawer) with your library and I am unable to use the `.attachNavigationDrawerToMenuButton(mDrawerLayout)` method as the other library is not a `DrawerLayout`. That's not a problem.

When I set a click listener for the left action and open the other drawer, your left action animates to show a back button. When I close the MaterialDrawer, it displays a back button which does nothing. Upon clicking it nothing happens. Is there some way to disable it from displaying the back button on click and just keeps displaying the menu?

```
<com.arlib.floatingsearchview.FloatingSearchView
        android:id="@+id/floating_search_view"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:floatingSearch_leftActionMode="showHamburger"
        app:floatingSearch_searchHint="Search..."
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>
```

```
floatingSearchView.setOnSearchListener(this);
        navigationDrawer = new DrawerBuilder().withActivity(mView.getActivity()).build();
        floatingSearchView.setOnLeftMenuClickListener(new FloatingSearchView.OnLeftMenuClickListener()
        {
            @Override
            public void onMenuOpened()
            {
                navigationDrawer.openDrawer();
            }

            @Override
            public void onMenuClosed()
            {
                // this is only called when the back button is clicked, but the drawer is already closed by this point
                navigationDrawer.closeDrawer();
            }
        });
```

**Comment by arimorty** [comment]
Thanks @jbmlaird , because of this confusion the attach API was added. Since you can't use the attach method, just follow the internal implementation [here](https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L1927) and apply it to the library you use.

Regards,
Ari
