### ISSUE TITLE
Using Glide invokes ClassCastException

### ISSUE THREAD

**Issue by shifatul-i** [arimorty/floatingsearchview#186]
Using ([Glide](https://github.com/bumptech/glide))
`Glide.with(getContext()).load(R.drawable.sample).centerCrop().into(ivMain);`
on ScrollingSearchExampleFragment
invokes an error in onBackPressed() - MainActivity
`BaseExampleFragment currentFragment = (BaseExampleFragment) fragments.get(fragments.size() - 1);
`

Error:
`java.lang.ClassCastException: com.bumptech.glide.manager.SupportRequestManagerFragment cannot be cast to com.demo.app.fragments.BaseExampleFragment
                                           at com.demo.app.MainActivity.onBackPressed(MainActivity.java:159)`

**Comment by arimorty** [comment]
@ThunderRoid it appears that that library adds a view-less fragment as part of it's request mechanism, so it makes sense for the cast error to happen. But sir, this is an issue in the sample project that is intended for quick illustration, it's not intended for anything other than to serve as a documentation. If you change code there, nothing is guaranteed to work. Feel free to experiment with different ways to handle back presses in the example.

All the best,
Ari

**Comment by shifatul-i** [comment]
OK, I will try to figure something out, and let you know if I get something solid. Thank for the awesome library though.
