### ISSUE TITLE
Hamburger icon and margin problems

### ISSUE THREAD

**Issue by EpsilonOrionis** [arimorty/floatingsearchview#190]
Hi @arimorty, I'm using your library and I'm new with it. I'm specifing in the xml to show the hamburger icon and to set the margin, but I don't see any effect, the FloatingSearchBar is the same. How can I solve this problem?

Thanks in advance :)

**Comment by arimorty** [comment]
Hey @EpsilonOrionis can you provide some more info, will be glad to help if there is still an issue.

Ari
