### ISSUE TITLE
Toolbar is gone when I use FloatingSearchView

### ISSUE THREAD

**Issue by sunpeijie0** [arimorty/floatingsearchview#193]
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <android.support.v7.widget.Toolbar
        android:id="@+id/map_activity_toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:layout_alignParentTop="true"
        android:theme="@style/AppTheme.AppBarOverlay"
        app:popupTheme="@style/AppTheme.PopupOverlay"/>
    <com.baidu.mapapi.map.MapView
        android:id="@+id/bmapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clickable="true" />

    <com.arlib.floatingsearchview.FloatingSearchView
        android:id="@+id/floatingSearchView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:floatingSearch_menu="@menu/menu_search_view" />

</RelativeLayout>`

**Comment by arimorty** [comment]
Please make sure to follow the README and the provided example app. If you still have an issue, please provide more info, otherwise make sure to close this issue.

Thanks,
Ari
