### ISSUE TITLE
Collapse / Hide Floatingsearchview

### ISSUE THREAD

**Issue by shifatul-i** [arimorty/floatingsearchview#196]
Please take a look at Google Play Store (Top Chart) page
I think this will be a great addition to the library to be able to Collapse / Hide Floatingsearchview

Below are some sample images

![image](https://cloud.githubusercontent.com/assets/3328263/23574549/45034294-0034-11e7-8ce3-2fcf8b075383.png)

![image](https://cloud.githubusercontent.com/assets/3328263/23574552/4df40cda-0034-11e7-8e54-8292e5454c2b.png)

**Comment by rayliverified** [comment]
Implementing this requires a completely different library. Thankfully, what you are looking for already exists :D
https://github.com/Mauker1/MaterialSearchView
https://github.com/claudiodegio/MsvSearch
https://material.uplabs.com/posts/searchview

Hope this helps :+1:

**Comment by echthard** [comment]
Just hide the toolbar when the searchview gets focus and show the toolbar again when it loses focus. I do this by animating the toolbar up and down. It's not that hard. 


```

    public void hideToolbar() {
        final RelativeLayout.LayoutParams params = (RelativeLayout.LayoutParams) mToolbar.getLayoutParams();
        ValueAnimator animator = ValueAnimator.ofInt(params.topMargin, -mToolbar.getHeight());
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator valueAnimator) {
                params.topMargin = (Integer) valueAnimator.getAnimatedValue();
                mToolbar.requestLayout();
            }
        });
        animator.setDuration(Constants.MOVE_ANIMATION_DURATION);
        animator.start();

    }


    public void showToolbar() {
        final RelativeLayout.LayoutParams params = (RelativeLayout.LayoutParams) mToolbar.getLayoutParams();
        ValueAnimator animator = ValueAnimator.ofInt(params.topMargin, 0);
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator valueAnimator) {
                params.topMargin = (Integer) valueAnimator.getAnimatedValue();
                mToolbar.requestLayout();
            }
        });
        animator.setDuration(Constants.MOVE_ANIMATION_DURATION);
        animator.start();
    }
```
