### ISSUE TITLE
Issue Interaction with BottomBar from Roughike

### ISSUE THREAD

**Issue by Mastro92p** [arimorty/floatingsearchview#197]
I'm using BottomNaviagtion from Roughike, my app uses an activity and 3 fragments (displayed when one tab is selected). The problem i have is that when the keyboard is displayed the BottomBar get on Top of the image. Is there i can do to prevent this behavior 
![17141696_10154278763966497_1218872796_n](https://cloud.githubusercontent.com/assets/13126691/23575737/9a85c2b2-0068-11e7-9316-1a942ef2fc00.jpg)
 
Sorry for the shitty image

**Comment by kandreadou** [comment]
You need to add ```app:bb_behavior="underNavbar"``` to your BottomBar xml layout

**Comment by arimorty** [comment]
It looks like this issue should have been in a different repository. Please try to post issues only if it relates directly to this library.

Thanks,
Ari
