### ISSUE TITLE
Background shadow on focused search

### ISSUE THREAD

**Issue by Apisov** [arimorty/floatingsearchview#20]
Hi.
Can I remove shadow on focused search?

**Comment by arimorty** [comment]
Hi,

No, not at the moment. May I ask, why would you need it?

**Comment by Apisov** [comment]
Because of bad implementation from previous developer I can't make searchView to fit screen(for the shadow). How searchView has only space in toolbar and when it focused it's showing ugly small shadow. 

Hope I was clear enough :)

**Comment by arimorty** [comment]
`FloatingSearchView` is assuming that it takes up the entire screen, so it won't work for you unless you find a way to stretch it to the entire screen.

Regards,
Ari
