### ISSUE TITLE
SuggestionsTextColor not applyed

### ISSUE THREAD

**Issue by andreabellitto** [arimorty/floatingsearchview#203]
I have some trouble because SuggestionsTextColor is always invisible, every color i try to put it's the same, i'm using the code methos and not the xml one

**Comment by mikecoppola16** [comment]
I'm having same issue, did you resolve it?

**Comment by andreabellitto** [comment]
No, still the same problem! I'm thinking about to use another working
library, this is a seriuos issue and it is so long now without solution.

Il 28 mar 2017 7:28 PM, "mikecoppola16" <notifications@github.com> ha
scritto:

**Comment by mikecoppola16** [comment]
Oh man, I have tried them all and this seems to be the best one except for this issue. I'm going through closed issues now to see if answer is in there.

**Comment by mikecoppola16** [comment]
Hey @belandsoft  This works:

 mSearchView.setOnBindSuggestionCallback(new SearchSuggestionsAdapter.OnBindSuggestionCallback() {
            @Override
            public void onBindSuggestion(View suggestionView, ImageView leftIcon,
                                         TextView textView, SearchSuggestion item, int itemPosition) {
                textView.setTextColor(ContextCompat.getColor(SearchActivity.this, R.color.grey_6));
            }
        });

**Comment by andreabellitto** [comment]
@mikecoppola16: For me is not working

**Comment by andreabellitto** [comment]
I found the issue, the problem is not the color of the textview, but it's the size of the textview.

In this line:

https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/suggestions/SearchSuggestionsAdapter.java#L166

the variable `mBodyTextSizePx` equals to `0.0f` so the sudgestions body textview size is 0.

This is the real working workarround:

`mSearchView.setOnBindSuggestionCallback(new SearchSuggestionsAdapter.OnBindSuggestionCallback() {
@Override
public void onBindSuggestion(View suggestionView, ImageView leftIcon,
TextView textView, SearchSuggestion item, int itemPosition) {
textView.setTextColor(ContextCompat.getColor(SearchActivity.this, R.color.grey_6));
textView.setTextSize(TypedValue.COMPLEX_UNIT_DIP, 15.f);
}
});`

**Comment by arimorty** [comment]
Hey everybody, this is indeed an important issue, I missed it for some reason. Fix is in develop and will be delivered to maven in the next milestone.

Thanks for contributing.

Also, I created an Mastodon account for this library, just wanted to try it out.  I'll be posting updates about this library there https://mastodon.cloud/@FloatingSearchView please join and let me know how you are using the library and what you would want to see in future releases.

Best,
Ari
