### ISSUE TITLE
Porting it to Xamarin.Forms

### ISSUE THREAD

**Issue by vhugogarcia** [arimorty/floatingsearchview#204]
Hello friends,

Anybody knows if this amazing library has been ported to Xamarin.Forms?

Thanks in advance

**Comment by arimorty** [comment]
Hi @vhugogarcia .

Thanks for your recognition!

I know that an early version of it was ported [here](https://components.xamarin.com/view/FloatingSearchView) but it might be missing functionality that came in later versions.

Best,
Ari

**Comment by vhugogarcia** [comment]
Hi @arimorty ,

I'm collaborating on update it and create a demo for Xamarin.Android, once I get it done I will upload it to Github for the community, I will share the link with you in case you would like to share it as well. 

Amazing work on this library, btw! :)

Now, that I'm here, do you know what this issue could be in terms of Android? 
"Binary XML file line #1: Binary XML file line #1: Error inflating class android.support.design.widget.NavigationView"

Below is the C# code I'm using, I know it is know Java, but similar.
http://pastebin.com/ivxN3hLW

**Comment by arimorty** [comment]
I am not familiar with Xamarin, I can't really help here.

 Thanks for contributing,
Ari
