### ISSUE TITLE
Menu Item is initially collapsed into overflow icon, even when room

### ISSUE THREAD

**Issue by ghost** [arimorty/floatingsearchview#207]
I created a simple menu item 

`<item
        android:id="@+id/search_settings"
        android:orderInCategory="100"
        android:icon="@drawable/ic_tune_24dp"
        app:showAsAction="ifRoom" />`

No matter what value I use for showAsAction, when the app first starts the icon is hidden in the overflow icon menu. If I rotate my device (to re-create my activity), then my menu icon appears properly.

Note: this only happens if the Visibility of the FloatingSearchView is initially set to View.GONE.

**Comment by arimorty** [comment]
@wiseShepherd can you elaborate? What do you mean "Note: this only happens if the Visibility of the FloatingSearchView is initially set to View.GONE." ?

**Comment by indracs7** [comment]
I faced the same issue.
Make the layout View.INVISIBLE instead of View.GONE.
