### ISSUE TITLE
Completely remove left button (arrow, hamburger etc)

### ISSUE THREAD

**Issue by djdance** [arimorty/floatingsearchview#212]
Im using your great lib as an overlay.
I do not nedd in "back" button or hamburger.
I set it's color to white, but it still shows big empty space while focused.
Also I tried to set setLeftActionMode(SOME_WRONG_NUMBER); but it continue to show black icon and big padding while focused.

Please add an ability to completely hide left button in the new version, thanks.
p.s. Also to remove bottom line, please.
![device-2017-04-14-164450](https://cloud.githubusercontent.com/assets/2269720/25046547/aa997278-213a-11e7-878d-0c4a2c2e7628.png)

**Comment by djdance** [comment]
of course I can add this 

```
        mSearchView.setLeftActionMode(3);
        mSearchView.findViewById(R.id.search_bar_left_action_container).setVisibility(View.GONE);

```

**Comment by echthard** [comment]
Why don't you check what's available? 

`mSearchView.setLeftActionMode(FloatingSearchView.LEFT_ACTION_MODE_NO_LEFT_ACTION);`

**Comment by arimorty** [comment]
Thanks @echthard !

**Comment by djdance** [comment]
_> Why don't you check what's available?_
@echthard that's exactly what you can see on the screenshot.
it IS the result of LEFT_ACTION_MODE_NO_LEFT_ACTION

**Comment by echthard** [comment]
I see, you get that when you type a text. When you type a text, you should get an arrow pointing to the left as a left action mode. That's sort of a "cancel" to go back to the previous state (cancel the search action). This is the XML:

```
<com.arlib.floatingsearchview.FloatingSearchView
        android:id="@+id/floating_search_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:floatingSearch_close_search_on_keyboard_dismiss="true"
        app:floatingSearch_leftActionMode="noLeftAction"
        app:floatingSearch_menu="@menu/menu_search"
        app:floatingSearch_searchBarMarginLeft="4dp"
        app:floatingSearch_searchBarMarginRight="4dp"
        app:floatingSearch_searchBarMarginTop="-2dp"
        app:floatingSearch_searchHint="Search"
        app:floatingSearch_showSearchKey="true"
        app:floatingSearch_suggestionsListAnimDuration="250" />
```

**Comment by djdance** [comment]
I know it all, that's why Im asking to add a 5-th case to remove this arrow completely. 
Actually I can remove it by the hack above, but this is ridiculous.

**Comment by echthard** [comment]
I'm sorry, I understand it now. However it's weird that you don't want to be able to cancel the search (remove all suggestions and lose focus from search view). Because when you'll press BACK button, it will be the same as pressing the arrow pointing to the left.

But it is something different and could be added to the lib. However, I think it's weird behaviour and not consistent with other (Google) apps.
