### ISSUE TITLE
Expose MenuItem

### ISSUE THREAD

**Issue by usernotnull** [arimorty/floatingsearchview#215]
I know this feature has been requested a couple of times, but if it's not that difficult, I don't see the reason why not. The features we can add to this great library include:
- adding badges to the menu items (something many apps are currently already doing with their persistent search bars
- changing icons programmatically 
- using a showcase view on top of each item
- manually disabling/hiding items programmatically (without re-inflating)
 
These don't have to be included in the library since a library should aim to be as abstract and transparent as possible as yours is, but exposing the MenuItems would benefit us a lot.
Unfortunately the badge feature is a necessity for my app so I can't use this library

**Comment by elirehema** [comment]
@arimorty can you promiss me that this please
