### ISSUE TITLE
Alternative search suggestion view

### ISSUE THREAD

**Issue by echthard** [arimorty/floatingsearchview#216]
Hi,

I would like to change the suggestion list view. Now it's 1 result per row, but I would like to have some kind of small buttons, or "chips" in a FlexBoxLayout. Something like this : 

![image](https://cloud.githubusercontent.com/assets/1479483/25087430/2ab09960-236f-11e7-8f24-0597e6066c67.png)

**Comment by arimorty** [comment]
@echthard 

Your suggestion is too radical of a change for this library at this point. But you can do something like this:
```
mSearchView.setOnBindSuggestionCallback(new SearchSuggestionsAdapter.OnBindSuggestionCallback() {
            @Override
            public void onBindSuggestion(View suggestionView, ImageView leftIcon,
                                         TextView textView, SearchSuggestion item, int itemPosition) {


                View view = LayoutInflater.from(suggestionView.getContext()).inflate(R.layout.your_layout, null);

                ((LinearLayout)suggestionView).removeAllViews();
                ((LinearLayout)suggestionView).addView(view);
     }

        });
```

Granted, not the best solution or event maybe not efficient to inflate dynamically on every bind, but you can use some creativity to come up with a solution. The idea is that you will get the same smooth slide down animation. In addition, I think the code in the project is understandable enough so you can download the project and mess around to come up with a solution for your needs.


Good luck,
Ari
