### ISSUE TITLE
The Sample App Does Not Build

### ISSUE THREAD

**Issue by adam-hurwitz** [arimorty/floatingsearchview#219]
This is the error that keeps throwing when I try to run the sample app provided.

Error:(25, 0) Could not read script '/Users/ahurwitz/Android/Samples/floatingsearchview/library/**maven-push.gradle**' as it does not exist.
<a href="openFile:/Users/ahurwitz/Android/Samples/floatingsearchview/library/build.gradle">Open File</a>

Do I need to change something in my **build.gradle** file or is this a bug with the sample code?

**Comment by spiralni** [comment]
Hi @AdamSHurwitz, I had the same problem,
just delete the line  maven-push.gradle in the build.gradle
