### ISSUE TITLE
Clear button

### ISSUE THREAD

**Issue by inlacou** [arimorty/floatingsearchview#22]
Hi,

First of all, nice work.

I see a problem with the clear button. It shows only after writing or deleting something on the search view, and not when clicking on it while something is displayed.

I have looked at other issues. I set a custom clear button as menu item and hide the usual clear button with `setClearBtnColor(Color.TRANSPARENT);`. In this case, the white place for the usual clear button is still here, removing place for text.

Is there something else I can do?

(Sorry for my english)

**Comment by arimorty** [comment]
I am glad you find it useful!

The clear button it is still there, so it will take away the room for text. It was only a workaround  mentioned in one of the issues.

For now, there is no solution for your problem, but I hope to get back to work on the library (I didn't work on it for a while) and make that and other things more flexible.
