### ISSUE TITLE
Suggestion text size is so small

### ISSUE THREAD

**Issue by poltographer6** [arimorty/floatingsearchview#220]
How to edit suggestion text size? it is very small.

![screenshot_2017-04-25-10-19-05](https://cloud.githubusercontent.com/assets/26056672/25366209/bba5b57c-29a0-11e7-959a-f4a59a0b88ea.jpg)

**Comment by arimorty** [comment]
Hi @poltographer6 

I am not sure why your suggestion text is so small, but your have full control of the `TextView` used to display the text by adding a listener `mSearchView.setOnBindSuggestionCallback() ` 

Best,
Ari

**Comment by poltographer6** [comment]
Thanks! :)
