### ISSUE TITLE
Displaying a map under the FSV

### ISSUE THREAD

**Issue by greg-stein** [arimorty/floatingsearchview#223]
Hi, 

Sorry for dumb question. I'm trying to use FSV just like in Google Maps app without success. The main issue is that I'm rendering my map with OpenGl on a custom GLSurfaceView. How can I layout this GL view so that the search bar appear on top of it (like in Google Maps app)?

Thank you very much,

Kindest regards, Greg.

**Comment by greg-stein** [comment]
In case I wasn't clear, I want to achieve this:
So that map is behind and around the search bar.

![image](https://cloud.githubusercontent.com/assets/15869727/25588232/26667572-2eb0-11e7-846f-ed076ca3948a.png)

**Comment by arimorty** [comment]
Hi @onirtuen ,

No question is dumb, but it's always better have a peek at the library's sample app. You need to make the search view overlap your other view (in your case the `GLSurfaceView`) one way of doing it is by using a `FrameLayout` and putting the search view below the `GLSurfaceView` in the view hierarchy in xml.

Good luck,
Ari
