### ISSUE TITLE
Libreria FloatingSearchView

### ISSUE THREAD

**Issue by laguilera0** [arimorty/floatingsearchview#224]
Buenas, me gustaria saber donde o como puedo obtener el lib offline de la libreria.Gracias

**Comment by marconi1992** [comment]
Necesitas clonar el repositorio abrirlo con android studio y hacer el build, esto te generaria un .aar.
Tambien aqui te dejo el .aar, https://drive.google.com/file/d/0B-zL4XdFr92sTVhIR3U4dzFzUWM/view?usp=sharing

**Comment by marconi1992** [comment]
@arimorty  I think this issue could be closed.

**Comment by arimorty** [comment]
Thanks @marconi1992 because I don't have the time to translate issues.
