### ISSUE TITLE
Scroll behaviour

### ISSUE THREAD

**Issue by d3bt3ch** [arimorty/floatingsearchview#236]
How can I hide the FSV on recycler view scoll ?

**Comment by arimorty** [comment]
Have you looked at the samples? Please refer to the samples before creating an issue.

More specifically, you want to look at [this](https://github.com/arimorty/floatingsearchview/blob/master/sample/src/main/java/com/arlib/floatingsearchviewdemo/fragment/ScrollingSearchExampleFragment.java#L244) one. But keep in mind that this is just one way of doing it.


Best,
Ari Cheshin
