### ISSUE TITLE
How to change the search hint size?

### ISSUE THREAD

**Issue by HanderWei** [arimorty/floatingsearchview#26]
Any help will be highly appreciate!

**Comment by arimorty** [comment]
I am not actively maintaining the project at the moment and the hint text size is fixed, so here is what you can try (I can't promise that it will play nicely but give it a try):

First obtain a reference to the EditText that is holding the query and hint (both are on the same EditText), and then set its size. Something like:

`EditText editText = (EditText)mSearchView.findViewById(R.id.search_bar_text);        editText.setTextSize(getResources().getDimensionPixelSize(R.dimen.your_hint_text_size));`

Keep in mind that the query text is using the same EditText, so reset it when appropriate.

**Comment by HanderWei** [comment]
Thx！
