### ISSUE TITLE
Search view should be closed on back key

### ISSUE THREAD

**Issue by jakubkrolewski** [arimorty/floatingsearchview#27]
1. Open the demo app
2. Tap on the search view to open it
3. Tap back - keyboard is closed
4. Tap back again - the application is closed

Expected behaviour:
tapping back when the search view is opened should close the search view, not the application

**Comment by laurentiuonac** [comment]
You can close it by listening for onBackPressed() events.

The following code checks if the search bar is focused and closes it if necessary.

```
if (mSearchFSV.isSearchBarFocused()) {
    mSearchFSV.clearSearchFocus();
    return;
}
```
