### ISSUE TITLE
showSearchHintWhenNotFocused attribute is missing

### ISSUE THREAD

**Issue by ugurcany** [arimorty/floatingsearchview#29]
It seems that the attribute "app:floatingSearch_showSearchHintWhenNotFocused" does not exist anymore. How can I set hint text hidden when searchview is not focused? I still want to see my search text even when focus is gone.

**Comment by arimorty** [comment]
Sorry for late response, I took a break from maintaining the library. 

So, you are right, the text should still be there when search is complete, and it will be this way in the next release (2.2.0). For now, you can use mFloatingSearchView.setSearchBarTitle(mSavedQuery); right after the suggestion is clicked.
