### ISSUE TITLE
Search touched event

### ISSUE THREAD

**Issue by ghost** [arimorty/floatingsearchview#297]
I was trying to find the event for when user clicks on search text to write something but trying some of events wasn't successful. is there any event for this?
(I want to use this event to open Google places selection activity.)

**Comment by jasontrask** [comment]
Setting the `onFocusChangeListener` should help you here...

```java
mFloatingSearchView.setOnFocusChangeListener(new FloatingSearchView.OnFocusChangeListener() {
  @Override
  public void onFocus() {
    System.out.println(" >>> Focus...");
  }

  @Override
  public void onFocusCleared() {
    System.out.println(" >>> Focus cleared...");
  }
});
```

**Comment by ghost** [comment]
@jasontrask Thanks. it seems there were two FocusEvent listeners and i have tried the other one and it wasn't working.
