### ISSUE TITLE
Implementing Suggestions

### ISSUE THREAD

**Issue by jabi1995** [arimorty/floatingsearchview#328]
I have a list of Strings fetched from local database How can I use this list as suggestion in FSV?
In your example I watched you convert Json format to ColorWrapper but How about mine?

Regards

**Comment by mosesmwongela** [comment]
Do this.

1. Create an entity class for your String. Something like: https://raw.githubusercontent.com/arimorty/floatingsearchview/master/sample/src/main/java/com/arlib/floatingsearchviewdemo/data/ColorSuggestion.java

2. Create an ArrayList of type "your entity"

3. Populate this arrayList

4. Pass this list to the FSV this way: mSearchView.swapSuggestions(newSearchSuggestions);

I hope this helps
