### ISSUE TITLE
Allow for scrolling suggestions without closing the keyboard

### ISSUE THREAD

**Issue by jakubkrolewski** [arimorty/floatingsearchview#34]
1. Open the demo app
2. Type "s"
3. Start scrolling suggestions

Result: keyboard is closed.

I think that this is not a desired behaviour. On modern devices a user has usually enough space for suggestions even if the keyboard is opened and closing it adds an additional step if a user wants to continue typing.
If you don't agree with it, I think there should be at least an option for configuring this feature in the library, so that the client app can decide which behaviour is preferred.

**Comment by n-belokopytov** [comment]
Half a year later - still not working.
