### ISSUE TITLE
Pair with drawer layout possible?

### ISSUE THREAD

**Issue by jensneuse** [arimorty/floatingsearchview#4]
Hey, can I easily pair your view with drawerToggle?

**Comment by arimorty** [comment]
Have a loot at the sample code, it has a drawer and some explanation. https://github.com/arimorty/floatingsearchview/blob/master/sample/src/main/java/com/arlib/floatingsearchviewdemo/MainActivity.java 

Basically, you can listen for menu clicks and then manually open the drawer.
