### ISSUE TITLE
I want to use the searchview as a toolbar

### ISSUE THREAD

**Issue by vbn92** [arimorty/floatingsearchview#46]
Without using the suggestions, I want to use the searchview with a recyclerview under it. Anyone know how to position the recyclerview under the searchview?

**Comment by ernestkamara** [comment]
It all depends on what other views you have in your Layout, but this works for me!
I use it for my SearchFragment and works well. The FloatingSearchView hides/shows while scrolling just as the Google+ app.

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true">
    <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center_horizontal"
            android:clipToPadding="false"
            android:paddingTop="60dp"
            android:paddingLeft="1dp"
            android:paddingRight="1dp"
            />
    <com.arlib.floatingsearchview.FloatingSearchView
            android:id="@+id/floating_search_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentTop="true"
            app:floatingSearch_searchBarMarginLeft="2dp"
            app:floatingSearch_searchBarMarginTop="4dp"
            app:floatingSearch_searchBarMarginRight="2dp"
            app:floatingSearch_showSearchKey="true"
            app:floatingSearch_dismissOnOutsideTouch="true"
            app:floatingSearch_leftActionMode="showHome"
            />
</RelativeLayout>
```

Show us your Layout and we may help you achieve your goal!

**Comment by arimorty** [comment]
@ernestkamara's suggestion is the one I used in my own projects as well. But I do want to provide a more out-of-the box solution for that, so that clients won't have to guess the padding top. 

This is one of the things I want to add in release 2.3.0. I also want to share my goals for that release in a wiki page and open it for suggestions.

**Comment by LOG-TAG** [comment]
@ernestkamara  works fine !! Thank you , any solution for removing shadow focus (to avoid user to click 2 times on the RecyclerView to select Item !!!
