### ISSUE TITLE
Search Results not correct

### ISSUE THREAD

**Issue by avtarsingh1122** [arimorty/floatingsearchview#49]
I somehow editted your sample code and used it with ArrayList<String> and its working fine. But my problem is that, its not showing suggestions if I start typing a word from in between of it.
For Example...
ArrayList contains "abc", "abcd", "bcd" (without inverted commas)
Now, if I type "bc" its showing me only "bcd" and not the 1st two
How can I fix this ?

**Comment by joydeepsaha05** [comment]
You could loop through the arrayList and check whether the search query is a substring of the string present in the search query.
