### ISSUE TITLE
Menu item voice showAsAction="always" icon disappears(alpha = 0)

### ISSUE THREAD

**Issue by drjunior** [arimorty/floatingsearchview#50]
Somehow after clicking on voice action item, clearing focus from searchView, showing suggestions, clearing suggestions and clicking again on voice action menu item the menu item disappears.
The button is there because when I click on it the selector appears but the button doesn't because it has alpha = 0.
How can I circumvent this problem? 
Thanks.

**Comment by arimorty** [comment]
What version of the library are you on?

**Comment by drjunior** [comment]
The latest, version 1.1.2

**Comment by arimorty** [comment]
It would help if you can provide step-by-step directions for reproducing the issue.

**Comment by drjunior** [comment]
I can actually do better. I've just recorded a video where you can see that the search icon disappears after animating the searchview.

https://vid.me/keI0

**Comment by arimorty** [comment]
It looks like a very weird bug, thanks for the vid. I'll look into it and reproduce it on my machine later and get back to you.

**Comment by ihainan** [comment]
Same problem in my Genymotion VMs and it worked fine on real devices.

**Comment by arimorty** [comment]
I am trying to reproduce this behavior unsuccessfully. @drjunior are you experiencing this in Genymotion only, or on physical device/s as well?

**Comment by drjunior** [comment]
Actually I can only reproduce it in genymotion emulators.

**Comment by arimorty** [comment]
@drjunior this turned out to be a defect in the code. It was fixed and is now available in the latest release.
