### ISSUE TITLE
Manifest conflicts in AutoFitTextView

### ISSUE THREAD

**Issue by TheRishka** [arimorty/floatingsearchview#54]
Hi! I'm trying to implement this awesome library in my project, but right after I added FloatingSearchView to my gradle dependencies, I've faced error:

```
Error:Execution failed for task ':app:myprocess'.
 Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:33:9-36
    is also present at [me.grantland:autofittextview:0.2.0] AndroidManifest.xml:11:18-44 value=(true).
```

It's pretty self-explanatory. I've checked AutoFitTextView library, and they have removed `allowBackup=true` from their manifest in [this commit](https://github.com/grantland/android-autofittextview/commit/067e92b0a011e52cff9724934234cffda972866a). So, please, update it in your project.

**Comment by TheRishka** [comment]
As a temporary workaround consider moving your dependency for FloatingSearchView on top of the dependencies list in your build.gradle.

**Comment by arimorty** [comment]
This won't be an issue in the next release which will come in the next couple of days. AutoFitTextView will be removed from FloatingSearchView completely as it  is not used anymore.
