### ISSUE TITLE
Question: FloatingSearchView behavior with RecyclerView

### ISSUE THREAD

**Issue by marcellogalhardo** [arimorty/floatingsearchview#56]
Hi, Good Morning. I'm using the FloatingSearchView on a Activity that has a RecyclerView. I'm having trouble doing two things:
1. Defining a behavior to hide it when an user scroll the RecyclerView?
2. How to separate a space at the top of the screen so that the SearchView not get over the first item in the list? And allow to scroll to the items to be played below the SearchView?

Sorry for my English. Thanks!

**Comment by arimorty** [comment]
Hi @marcellogalhardo 
1. This library does not support this behavior, but it will be part of the milestone 2.3.0. This means that release 2.2.0 that contains some important stability improvements will be released first, and then the focus will be on 2.3.0 which will contain new features (including what you mentioned) Hopefully release 2.2.0 will be out within a week.
2. This can be done easily by adding paddingTop to your RecyclerView as mentioned [here](https://github.com/arimorty/floatingsearchview/issues/46#issuecomment-221489475)

I hope your questions were answered.

**Comment by marcellogalhardo** [comment]
You answered my questions. I'll be watching for the release of Release 2.3.0.
Thank you.
