### ISSUE TITLE
onSearchAction() not working

### ISSUE THREAD

**Issue by kuraydev** [arimorty/floatingsearchview#57]
Hello, 
I love your project and i'm using it. I have a big issue, i cannot search by onSearchAction listener it never enters in it. Therefore, i have to use onFocusCleared method but it gives me lots of bugs such as, if i give up to search and click anywhere it still search on it because of the focusClear can you help me about this issue.

Thank you so much.

**Comment by arimorty** [comment]
Hi, 

I am happy to hear that you find this library useful! 

A new release (2.0.1) with many fixes and some important improvements is coming soon (probably this week), and in that release the onSearchAction() will be passed the query. 

Regards,

**Comment by HanderWei** [comment]
Hi, @arimorty ! 
onSearchAction() still not working!

**Comment by arimorty** [comment]
@HanderWei in order to understand your issue, can you provide a step by step to reproduce your problem?

**Comment by abhriyaroy** [comment]
@arimorty Its working perfectly fine for me. Thank you so much.
