### ISSUE TITLE
Show arrow at start and disable hamburger icon

### ISSUE THREAD

**Issue by jd-alexander** [arimorty/floatingsearchview#6]
How do I disable the hamburger icon and only show the back arrow. My search activity won't contain a drawer so it's not necessary.

**Comment by arimorty** [comment]
This isn't directly supported yet, but stay tuned as it is very likely to be supported in release 1.1.0

**Comment by arimorty** [comment]
Release 1.1.0 now includes an option for that. Thanks for suggestions!

**Comment by jd-alexander** [comment]
Awesome! Realy nice.

**Comment by arimorty** [comment]
Thanks, please let me know of any problems.

**Comment by jd-alexander** [comment]
Okay will test it out and let you know.

**Comment by jd-alexander** [comment]
Is having a menu for the search bar mandatory?

**Comment by arimorty** [comment]
It shouldn't be, but I noticed the problem right after the release (: For now, just define an empty menu resource. I'll fix it in the following days.

**Comment by jd-alexander** [comment]
okay will do just that.
