### ISSUE TITLE
Can we go back to previous activity  directly when the search view is focused?

### ISSUE THREAD

**Issue by galihuotui** [arimorty/floatingsearchview#63]
Hi , when we use the floating search view ,  can we just listen to the left arrow when the view is focused , if we do not want to click the left arrow twice when we want to go back to the previous activity ,  can we do that ?

**Comment by arimorty** [comment]
Hi @cuikangyuan ,

Using [this](https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L1612) you can listen to when the search `View` clears focus and then close your activity.

**Comment by knaeckeKami** [comment]
For anyone else left confused by this answer: The referenced method was "setOnFocusChangeListener", one can listen to onFocusCleared() with this method.
Because of recent commits, the referenced line changed and was referencing an unrelated private method at the time of my comment.

**Comment by arimorty** [comment]
@knaeckeKami thanks for pointing that out! I fixed the link.

Regards,
