### ISSUE TITLE
1 Feature Request and 1 Bug

### ISSUE THREAD

**Issue by iambriccardo** [arimorty/floatingsearchview#64]
Bug: if i inserted the searchview above a static shape the shadow of the searchview is located only at the margins of the search. 

Feature: add option to disable the suggestions, because on my layout I can't set in the best way my items because I see a big card with recyclerviewer that block me! That's all

**Comment by arimorty** [comment]
Hi @RiccardoBusetti , 

It is hard to tell the bug and feature you are describing. Can you provide more info or screenshots of the bug and why you need the feature?

**Comment by iambriccardo** [comment]
How i can upload photos from mobile?

**Comment by iambriccardo** [comment]
![screenshot_20160605-190308](https://cloud.githubusercontent.com/assets/15819674/15806961/4d6fb322-2b50-11e6-8eb5-88576fe1ae33.png)

**Comment by iambriccardo** [comment]
Look at the shadow!

**Comment by arimorty** [comment]
I see. Does the `FloatingSearchView` cover the entire screen as specified [here](https://github.com/arimorty/floatingsearchview/blob/master/README.md#usage) in step 2?

**Comment by iambriccardo** [comment]
Look here: https://github.com/RiccardoBusetti/Colombo
https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FRiccardoBusetti%2FColombo&sa=D&sntz=1&usg=AFQjCNGRx0M_JcOW28qGWqvfSps2cyRhwg
Il 05 giu 2016 10:37 PM, "Ari" notifications@github.com ha scritto:

**Comment by arimorty** [comment]
In order for `FloatingSearchView` to work, you want to place the view at the very end of your top layout in a way that the view overlaps all your other views. Also, for margins, use the margin attributes provided by the view like `floatingSearch_searchBarMarginLeft`.

Please refer to the provided sample code before posting issues, but I am happy to answer any further questions.

Regards,

**Comment by iambriccardo** [comment]
Thanks i will try :)
Il 05 giu 2016 11:48 PM, "Ari" notifications@github.com ha scritto:

**Comment by iambriccardo** [comment]
![schermata 2016-06-07 alle 19 38 50](https://cloud.githubusercontent.com/assets/15819674/15868306/928386da-2ce7-11e6-9836-af568531a26f.png)

Margin are setted the same!

**Comment by arimorty** [comment]
In `FloatingSearchView`, the shadow is part of the view that holds the search bar, so you have to subtract the shadow width from your desired padding. So, say you want an `8dp` margin, you subtract the shadow padding which is about `3dp`, and set the `FloatingSearchView`'s margin to `5dp`.

Again, it is included in the sample here https://github.com/arimorty/floatingsearchview/blob/master/sample/src/main/res/layout/activity_main_main_content.xml#L34 , please look at the sample before creating new issues. 

Regards,
