### ISSUE TITLE
Call an action menu (added) to control its visibility in java code

### ISSUE THREAD

**Issue by VuHongKy** [arimorty/floatingsearchview#66]
Hi @arimorty 
I added an item (action menu) to main_menu.xml and set it to searchView bar.
Now I want to call that action menu by searchView to control it. For example, I want to show it when run a task, and hide it when task completed.
Any idea? I don't know how to do that, please help me.

**Comment by arimorty** [comment]
Hi VuHongKy,

You can use https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L983 to inflate menus dynamically.

Regards,

**Comment by VuHongKy** [comment]
Sorry @arimorty 
But I added an menu_item to main_menu and add to searchView. And I want to ask how to call an menu_item in java code for set its visibility. For example, my menu_item is action_cancel_search_task.
It means I want to call an menu button (cancel task) to hide it or show it. How can I do that?
Thanks @arimorty
