### ISSUE TITLE
setOnHomeActionClickListener is not working

### ISSUE THREAD

**Issue by santoshgupta901** [arimorty/floatingsearchview#67]
I set setOnHomeActionClickListener on floating searchView but it is not working.

**Comment by VuHongKy** [comment]
Me, too. Haizz.
@arimorty Please help. It is a basic feature, man.

**Comment by arimorty** [comment]
That listener is only called when the `FloatingSearchView` is not focused and when             `app:floatingSearch_leftActionMode="showHome"` You might want to look at this similar question: https://github.com/arimorty/floatingsearchview/issues/63
