### ISSUE TITLE
A library uses the same package

### ISSUE THREAD

**Issue by rakesh779** [arimorty/floatingsearchview#68]
Error:Execution failed for task ':library:processDebugResources'.

> Error: A library uses the same package as this project: com.arlib.floatingsearchview

![issues](https://cloud.githubusercontent.com/assets/19783087/15831835/1fa3d9f8-2c3d-11e6-8708-37db4214321c.jpg)

**Comment by arimorty** [comment]
@rakesh779 can you look at issue #45 and let me know if it is related to your issue?
