### ISSUE TITLE
Progress icon display duplicate on Search or Home Icon

### ISSUE THREAD

**Issue by VuHongKy** [arimorty/floatingsearchview#69]
Hi @arimorty 
When I do a search task, I call showProgress(), and display spin progress icon. But when the task is not done, I focus on search text, and Home or Search Icon display, too. 
And they (progress icon & search icon) display at exactly same position.
I want to hide search icon or move it next progress icon, how could I do that?
Many thanks, @arimorty

**Comment by arimorty** [comment]
Hi @VuHongKy ,

The library should not show the left icon when progress is ongoing, I added a fix for that.

Thanks!
