### ISSUE TITLE
Touch problem in Microphone and X icons

### ISSUE THREAD

**Issue by Pabloku** [arimorty/floatingsearchview#7]
Hi!

Just to let you know that I am seeing a weird behaviour in those icons when setting a floating search view like this:

<com.arlib.floatingsearchview.FloatingSearchView
        android:id="@+id/floating_search_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:floatingSearch_searchBarMarginLeft="10dp"
        app:floatingSearch_searchBarMarginTop="10dp"
        app:floatingSearch_searchBarMarginRight="10dp"
        app:floatingSearch_showMenuAction="false"
        app:floatingSearch_searchHint="Search..."
        app:floatingSearch_voiceRecHint="Say something..."
        app:floatingSearch_showSearchHintWhenNotFocused="true"
        app:floatingSearch_showVoiceInput="true"
        app:floatingSearch_showOverFlowMenu="false"
        app:floatingSearch_hideOverflowMenuWhenFocused="false"
        app:floatingSearch_showSearchKey="true"
        app:floatingSearch_dismissOnOutsideTouch="true"/>

The problem is that the right icon (microphone or x icon if you have written something) are very difficult to click. Something weird I think but sure you can solved it for next version ;)

Keep the good work!

Thanks!

**Comment by arimorty** [comment]
All the icons in the search bar are going to go through a complete overhaul in next release 1.1.0 to add some very interesting features (You are going to like it :)) along with some bug fixes. Depending if I have time, the release will probably come within a week or two. Your problem will be resolved along with the release.

**Comment by Pabloku** [comment]
Hope so then! Thanks very much!

**Comment by arimorty** [comment]
This problem was fixed in release 1.1.0. Thanks for reporting.
