### ISSUE TITLE
dimming color

### ISSUE THREAD

**Issue by hatak30** [arimorty/floatingsearchview#71]
Hi

Is it possible to turn off dimming when you click on search bar?

**Comment by arimorty** [comment]
Hi,

Yes. Have you looked at the sample? It is using the attribute https://github.com/arimorty/floatingsearchview/blob/master/sample/src/main/res/layout/activity_main_main_content.xml#L40 which has the corresponding public method https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L1048

**Comment by hatak30** [comment]
thanks, I haven't checked that, very cool library :)
