### ISSUE TITLE
Is it possible to get MenuView?

### ISSUE THREAD

**Issue by christarazi** [arimorty/floatingsearchview#73]
I want to be able to access the View responsible for the menu. In the code, it's called `mMenuView`. The reason I want to access it is because I'm using [MaterialShowcaseView](https://github.com/deano2390/MaterialShowcaseView), and I want to be able to 'showcase' the menu buttons inside the FloatingSearchView. 

To use MaterialShowcaseView, you do something like this:

``` java
sequence.addSequenceItem(buildShowcaseView(aView, new RectangleShape(0, 0),
                "Enter any zip code, city, or address here."
        ));
```

where `aView` is the View you want to 'showcase'.

The above code will do something like this: 
http://i.imgur.com/XJtwCE3l.png
![image](http://i.imgur.com/XJtwCE3l.png)

I'd like 'showcase' the individual buttons.

When I try to access the menu items directly via `mFloatingSearchView.findViewById()`, it returns a null pointer.

So I'm assuming that I need the actual `MenuView` to be able to do a `findViewById`.

Does anyone know if this is possible?

**Comment by arimorty** [comment]
Hi @christarazi ,

The `MenuItem`s are currently not exposed, so it would be difficult or impossible to get a reference to them.
