### ISSUE TITLE
Graphical bugs

### ISSUE THREAD

**Issue by ylichadeev** [arimorty/floatingsearchview#77]
![image](https://cloud.githubusercontent.com/assets/5028893/16068529/3fafaaf4-32cf-11e6-836f-69edae048886.png)
![image](https://cloud.githubusercontent.com/assets/5028893/16068535/51239548-32cf-11e6-8735-e5980517a85d.png)
At launch fragment

**Comment by ylichadeev** [comment]
And can u add ellipsize end of search string? 
![image](https://cloud.githubusercontent.com/assets/5028893/16068592/bf61c476-32cf-11e6-957e-cf20112e9b50.png)

**Comment by arimorty** [comment]
Hi @needsst , 

These graphical bugs have the highest priority right now. The first and last issues only occur in pre-L, the middle one I am having trouble reproducing so it would be helpful if you can provide a step-by-step for reproducing it.

Thanks for reporting

**Comment by arimorty** [comment]
@needsst for clarity and sanity purposes, can you create a new feature issue for "And can u add ellipsize end of search string? "

Thanks for contributing,
Ari
