### ISSUE TITLE
How to Implement SearchSuggestion

### ISSUE THREAD

**Issue by DarkSpam91** [arimorty/floatingsearchview#81]
Hello,
I hope this good, I need your help!
I have doubts about how to implement SearchSuggestion to do a new search and display it in a recycleview , I have to follow the same structure when android.support.v7.widget.SearchView use ?

**Comment by arimorty** [comment]
Hi @DarkSpam91,

In short, no. the `SearchView` does things completely differently, and at this moment, this library has nothing to do with that. With that in mind, this library might in the future connect to some of the features provided with the `SearchView` configuration.

Regards,
Ari
