### ISSUE TITLE
How does MenuItem and overflow item styling works?

### ISSUE THREAD

**Issue by ernestkamara** [arimorty/floatingsearchview#82]
Hi,
Am trying to change the Text color of the MenuItems in the overflow Menu. 
Is it possible to use the default app theme or what attribute to use to get it fixed.

Thanks

**Comment by arimorty** [comment]
Hi @ernestkamara , 

I haven't tried messing with the themes to get what you want working, but I'll look into it after the next release 2.0.2. If you look into the code you will see that I am using a `MenuPopupHelper` for creating the popup.

Regards

**Comment by ernestkamara** [comment]
Thanks. I managed to come up with a workaround for our current release. 
But would be nice to have some theming feature in the next releases.
