### ISSUE TITLE
Need a way to get the focus on search filed

### ISSUE THREAD

**Issue by manjunathc23** [arimorty/floatingsearchview#9]
Is there a way to open the keyboard and have the focus by default / programatically. ?
If not can you please expose a way to get the editor / edit text so that we can have some control over it. 

Thanks!
Manju

**Comment by arimorty** [comment]
It is definitely important to be able to set the focus of the search indeed, so I'll add it in the next release. I do not want to expose the EditText at this moment though.

Thanks for suggestions.

**Comment by manjunathc23** [comment]
Perfect! 

Just so that you know, I am going launching the search view in fragment so I need to open the keyboard when we launch the fragment. 

Thanks for your help!
Manju

**Comment by arimorty** [comment]
I would like to ask your opinion about https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/suggestions/model/SearchSuggestion.java.

Do you thing it is useful to have full access the the ImageView or the TextView for the SearchSuggestions? I am thinking of removing the ability to modify them because if client is changing certain attributes it could cause undesired results.

**Comment by manjunathc23** [comment]
I am glad you asked. I was wondering why we have the data and view mix up here. 

Well here is my opinion. Please feel free to correct me / debate with me if you don't agree for certain points noted down here

1 ) Quick fix 

I see the approach you have taken, This lib does not allow to set the `Adapter` from outside which I assume is the design choice.  Assuming you would go ahead with this approach further, I would recommend to have clear distinguish between view and data model. We should not mix up data to view model in anytime. It's always better to keep data model to be view agnostic. 

To fix the style / theme problem I would get the style / theme pre defined when the view is initialized or inflated in XML using the  `app:floatingSearch_suggestion_text_size`, `app:floatingSearch_suggestion_text_typeface` `app:floatingSearch_suggestion_text_color` etc. 
We should be able to set these programmatically too using some kind of setters methods. 

This would be much faster approach for now considering the amount of work you have put out there. 

2)  Refactor the design choice

Since this lib is in it's initial stage I think you should reconsider to refactor a little bit to get the suggestion adapter from the outside. This is how other android view works. Its gives a way to set the different `Adapter` based on the user needs. All you have do is to provide a way to set the text to search view and couple of wrapper listener on text change listener. 

Hope this helps!
If you feel to discuss more, you have my email id. Please feel free to contact me anytime. 
I think this library has huge potential to grow provided it has ability configure easily. 

Thanks!
Manju

**Comment by arimorty** [comment]
Thanks, I really appreciate your thoughts and your contributions to the library! This helps make the library better.

Best regards,
Ari
