### ISSUE TITLE
Clear button

### ISSUE THREAD

**Issue by kateryna-vovryn** [arimorty/floatingsearchview#91]
Please fix bug that clear search view button is showing only first time.

**Comment by Gloix** [comment]
I think pull requests #79 and #80 attempt to solve the issue, but the maintainer has shown no signs of life since May.

**Comment by arimorty** [comment]
Hi,

I was occupied with another project for a while and was unable to find time to properly maintain this project. I will look into all open issues and PRs this and next week and try to catch up.

Thanks for your contributions,
Ari

**Comment by ghost** [comment]
@arimorty yes please and thank you

**Comment by arimorty** [comment]
@VKatya I can't reproduce the issue, can you provide me with a step by step?

**Comment by fabriciointerama** [comment]
@arimorty I think it's the same as #78

**Comment by kateryna-vovryn** [comment]
Yes, it's the same issue

**Comment by arimorty** [comment]
OK, thanks. Will look into it.
