### ISSUE TITLE
how to avoid takes up the full height while it's initialized?

### ISSUE THREAD

**Issue by LOG-TAG** [arimorty/floatingsearchview#93]
In FloatingSearchView how to avoid 'takes up the full height ' or any way to display results when the screen is initialized ? I just want to avoid the empty blank screen below the FloatingSearchView screen when it is initialized !

For Ex: 

![screenshot_2016-07-16-18-36-07](https://cloud.githubusercontent.com/assets/1190344/16894953/95d8d5cc-4b84-11e6-8b2e-b070c15d2336.png)

**Comment by arimorty** [comment]
Hi @LOG-TAG , 

have you looked at #46 ?
